<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		  <LangVersion>14.0</LangVersion>
	</PropertyGroup>
	<ItemGroup>
	  <Folder Include="Assets\Sounds\Music\" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="ParticleLibrary">
	    <HintPath>Lib\ParticleLibrary.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<!-- References -->

</Project>